# Force Faster Travis-CI Container Infrastructure
sudo: false
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true
  include:
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # Until the next major stable image update
  allow_failures:
    - php: hhvm
    - php: 7.0
    - php: 7.0

before_script:
  - composer update

script:
  - ./vendor/bin/phpcs -p --report=full --extensions=php --standard=.travis/phpcs/Joomla/ruleset.xml src/
